apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-server
spec:
  selector:
    matchLabels:
      app: hello-world-server
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-server
    spec:
      containers:
        - name: hello-world-server
          image: jparengkuan/hello-world-server:main
          ports:
            - containerPort: 3000
