apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hello-world-server
  labels:
    app: hello-world-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: hello-world-server
    release: {{ .Release.Name }}