name: Repository Dispatch

on:
  repository_dispatch:
    types: [new-version]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Image Version
        id: imgupd
        uses: mikefarah/yq@master
        with:
          cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i hello-world-server/deployment.yaml

      - uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          commit_message: Apply image name changes
